[package]
name = "checklist"
version = "0.2.0"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.7.0"
dialoguer = "0.3.0"
duct_sh = "0.1.0"
failure = "0.1.0"
indicatif = "0.11.0"
maplit = "1.0.0"
scopeguard = "1.0.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_yaml = "0.8.0"
structopt = "0.2.0"

[dev-dependencies]
assert_cmd = "0.11.0"
assert_fs = "0.11.0"
lazy_static = "1.3.0"
rexpect = "0.3.0"
